[versions]
activity = "1.9.1"
androidGradlePlugin = "8.5.2"
compose = "2024.08.00"
core = "1.13.1"
espresso = "3.6.1"
firebase = "33.2.0"
googleServices = "4.4.2"
hilt = "2.51.1"
hiltNavigation = "1.2.0"
junit = "4.13.2"
junitAndroid = "1.2.1"
kotlin = "2.0.20"
kotlinCoroutines = "1.8.1"
kotlinSerialization = "1.6.3"
ksp = "2.0.20-1.0.24"
lifecycle = "2.8.4"
mockk = "1.13.12"
navigation = "2.8.0-rc01"
room = "2.6.1"
retrofit = "2.11.0"
testRules = "1.6.1"
truth = "1.4.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata"}
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
junit-test = { module = "junit:junit", version.ref = "junit" }
junit-test-android = { module = "androidx.test.ext:junit", version.ref = "junitAndroid" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
test-rules = { module = "androidx.test:rules", version.ref = "testRules" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[bundles]
compose = ["compose-material3", "compose-livedata", "compose-foundation", "compose-ui-tooling", "compose-ui-tooling-preview"]
lifecycle = ["lifecycle-ktx", "lifecycle-compose"]
